package calculation;

import java.awt.event.*;
import javax.swing.*;
/**
 *
 * @author José Felipe Flores da Silva
 */
public class Calcl extends javax.swing.JFrame {
    

    double num1, num2, result;
    String c;
    
    public Calcl() {
        initComponents();
        
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }
    
    
    
    public void keyPressed (KeyEvent e){
        int keyCode = e.getKeyCode();
        switch (keyCode){
            case (KeyEvent.VK_0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_ENTER): {jButtonEq.doClick();}
                break;
            case (KeyEvent.VK_DELETE): {jButtonAC.doClick();}
                break;
            case (KeyEvent.VK_BACK_SPACE): {jButtonDel.doClick();}
                break;
            case (KeyEvent.VK_PERIOD): {jButtonPoint.doClick();}
                break;
            case (KeyEvent.VK_PLUS): {jButtonAdd.doClick();}
                break;
            case (KeyEvent.VK_MULTIPLY): {jButtonMul.doClick();}
                break;
            case (KeyEvent.VK_SUBTRACT): {jButtonSub.doClick();}
                break;
            case (KeyEvent.VK_SLASH): {jButtonDiv.doClick();}
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonInvert = new javax.swing.JButton();
        jButtonAC = new javax.swing.JButton();
        jButtonDel = new javax.swing.JButton();
        jButtonMul = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonSub = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonEq = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jtxtDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonInvert.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonInvert.setText("+/-");
        jButtonInvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvertActionPerformed(evt);
            }
        });

        jButtonAC.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAC.setText("AC");
        jButtonAC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonACMouseEntered(evt);
            }
        });
        jButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACActionPerformed(evt);
            }
        });
        jButtonAC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonACKeyTyped(evt);
            }
        });

        jButtonDel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonDel.setText("←");
        jButtonDel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonDelMouseEntered(evt);
            }
        });
        jButtonDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelActionPerformed(evt);
            }
        });

        jButtonMul.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonMul.setText("X");
        jButtonMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMulActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton3KeyReleased(evt);
            }
        });

        jButtonDiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonDiv.setText("÷");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonSub.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonSub.setText("-");
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });

        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButton0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        jButton0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton0KeyPressed(evt);
            }
        });

        jButtonEq.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonEq.setText("=");
        jButtonEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqActionPerformed(evt);
            }
        });

        jButtonPoint.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jtxtDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jtxtDisplay.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jtxtDisplay.setForeground(new java.awt.Color(0, 0, 0));
        jtxtDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jtxtDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.darkGray, java.awt.Color.white, null, java.awt.Color.lightGray));
        jtxtDisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDisplayKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInvert, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEq, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInvert, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAC, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMul, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEq, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACActionPerformed
        jtxtDisplay.setText("");
    }//GEN-LAST:event_jButtonACActionPerformed

    private void jButtonDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelActionPerformed
        String a = jtxtDisplay.getText();
        String del = a.substring(0, a.length()-1);
        jtxtDisplay.setText(del);
        
    }//GEN-LAST:event_jButtonDelActionPerformed

    private void jButtonInvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvertActionPerformed
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
        if (!String.valueOf(ops).endsWith(".0")){
            jtxtDisplay.setText(String.valueOf(ops));
        } 
        else{
            jtxtDisplay.setText(String.valueOf(ops).substring(0, String.valueOf(ops).length()-2));
        }
    }//GEN-LAST:event_jButtonInvertActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton7.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton4.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton1.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton8.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton5.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton2.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton9.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton6.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton3.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        num1 = Double.parseDouble(jtxtDisplay.getText());
        jButtonDiv.setMnemonic('/');
        jtxtDisplay.setText("");
        c = "/";
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        c = "-";
    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        c = "+";
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButton0.getText();
        jtxtDisplay.setText(Enternumber);
        if (jtxtDisplay.getText().length()>12) {
            jtxtDisplay.setText(jtxtDisplay.getText().substring(0, 12));
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqActionPerformed
        String answer = "";
        num2 = Double.parseDouble(jtxtDisplay.getText());
        if (null != c) switch (c) {
            case "+":
                result = num1 + num2;
                answer = String.format("%.0f", result);
                break;
            case "-":
                result = num1 - num2;
                answer = String.format("%.0f", result);
                break;
            case "*":
                result = num1 * num2;
                answer = String.format("%.0f", result);
                break;
            case "/":
                result = num1 / num2;
                answer = String.format("%.0f", result);
                break;
            default:
                break;
        }
        
        String r = String.valueOf(result);
        if (!r.endsWith(".0")){
            jtxtDisplay.setText(r);
        }
        else{
            jtxtDisplay.setText(r.substring(0, r.length()-2));
        }
    }//GEN-LAST:event_jButtonEqActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        String Enternumber = jtxtDisplay.getText() + jButtonPoint.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButtonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMulActionPerformed
        num1 = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        c = "*";
    }//GEN-LAST:event_jButtonMulActionPerformed

    private void jButtonACKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonACKeyTyped
        
    }//GEN-LAST:event_jButtonACKeyTyped

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed

    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton0KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton0KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton0KeyPressed

    private void jButton3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3KeyReleased

    private void jtxtDisplayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyPressed
        int keyCode = evt.getKeyCode();
        switch (keyCode){
            case (KeyEvent.VK_0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_ENTER): {jButtonEq.doClick();}
                break;
            case (KeyEvent.VK_DELETE): {jButtonAC.doClick();}
                break;
            case (KeyEvent.VK_BACK_SPACE): {jButtonDel.doClick();}
                break;
            case (KeyEvent.VK_PERIOD): {jButtonPoint.doClick();}
                break;
            case (KeyEvent.VK_PLUS): {jButtonAdd.doClick();}
                break;
            case (KeyEvent.VK_MULTIPLY): {jButtonMul.doClick();}
                break;
            case (KeyEvent.VK_SUBTRACT): {jButtonSub.doClick();}
                break;
            case (KeyEvent.VK_SLASH): {jButtonDiv.doClick();}
                break;
        }
    }//GEN-LAST:event_jtxtDisplayKeyPressed

    private void jtxtDisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyTyped
        int keyCode = evt.getKeyCode();
        switch (keyCode){
            case (KeyEvent.VK_0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_ENTER): {jButtonEq.doClick();}
                break;
            case (KeyEvent.VK_DELETE): {jButtonAC.doClick();}
                break;
            case (KeyEvent.VK_BACK_SPACE): {jButtonDel.doClick();}
                break;
            case (KeyEvent.VK_PERIOD): {jButtonPoint.doClick();}
                break;
            case (KeyEvent.VK_PLUS): {jButtonAdd.doClick();}
                break;
            case (KeyEvent.VK_MULTIPLY): {jButtonMul.doClick();}
                break;
            case (KeyEvent.VK_SUBTRACT): {jButtonSub.doClick();}
                break;
            case (KeyEvent.VK_SLASH): {jButtonDiv.doClick();}
                break;
        }
    }//GEN-LAST:event_jtxtDisplayKeyTyped

    private void jtxtDisplayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDisplayKeyReleased
        int keyCode = evt.getKeyCode();
        switch (keyCode){
            case (KeyEvent.VK_0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD0): {jButton0.doClick();}
                break;
            case (KeyEvent.VK_1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD1): {jButton1.doClick();}
                break;
            case (KeyEvent.VK_2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD2): {jButton2.doClick();}
                break;
            case (KeyEvent.VK_3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD3): {jButton3.doClick();}
                break;
            case (KeyEvent.VK_4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD4): {jButton4.doClick();}
                break;
            case (KeyEvent.VK_5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD5): {jButton5.doClick();}
                break;
            case (KeyEvent.VK_6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD6): {jButton6.doClick();}
                break;
            case (KeyEvent.VK_7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD7): {jButton7.doClick();}
                break;
            case (KeyEvent.VK_8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD8): {jButton8.doClick();}
                break;
            case (KeyEvent.VK_9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_NUMPAD9): {jButton9.doClick();}
                break;
            case (KeyEvent.VK_ENTER): {jButtonEq.doClick();}
                break;
            case (KeyEvent.VK_DELETE): {jButtonAC.doClick();}
                break;
            case (KeyEvent.VK_BACK_SPACE): {jButtonDel.doClick();}
                break;
            case (KeyEvent.VK_PERIOD): {jButtonPoint.doClick();}
                break;
            case (KeyEvent.VK_PLUS): {jButtonAdd.doClick();}
                break;
            case (KeyEvent.VK_MULTIPLY): {jButtonMul.doClick();}
                break;
            case (KeyEvent.VK_SUBTRACT): {jButtonSub.doClick();}
                break;
            case (KeyEvent.VK_SLASH): {jButtonDiv.doClick();}
                break;
        }
    }//GEN-LAST:event_jtxtDisplayKeyReleased

    private void jButtonACMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonACMouseEntered
        jButtonAC.setToolTipText("Clear all");
    }//GEN-LAST:event_jButtonACMouseEntered

    private void jButtonDelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDelMouseEntered
        jButtonDel.setToolTipText("Erase last number");
    }//GEN-LAST:event_jButtonDelMouseEntered

    public void keyListener (KeyEvent e){
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Calcl().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonAC;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDel;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEq;
    private javax.swing.JButton jButtonInvert;
    private javax.swing.JButton jButtonMul;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JLabel jtxtDisplay;
    // End of variables declaration//GEN-END:variables

    
}
